upstream spring-blue {
    server spring-blue:8080;
}

upstream spring-green {
    server spring-green:8080;
}

# HTTP -> HTTPS redirection
server {
    listen 80;
    server_name NGINX_HOST;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS main
server {
    listen 443 ssl;
    include /etc/nginx/conf.d/service-url.inc;
    server_name NGINX_HOST;

    ssl_certificate /etc/letsencrypt/live/NGINX_HOST/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/NGINX_HOST/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;
    client_body_buffer_size 10M; # 10MB까지는 임시 파일 생성 없이 메모리에서 즉시 처리

    location / {
        proxy_pass http://$service_url;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_max_temp_file_size 0;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}