spring:
  application:
    name: TeumTeumEat
  datasource:
    username: tte_user
    password: tteswypdb123!
    url: jdbc:mysql://localhost:3307/teumteumeat
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 47a07455a424937d2fc6e37d3086829e
            client-secret: NONE # 카카오는 Secret이 필수가 아니면 임의값 또는 생략
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: # 필요한 동의 항목
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오 식별자 'id'
  apple:
    team-id: "TEMP_TEAM_ID"
    client-id: "TEMP_CLIENT_ID"
    key-id: "TEMP_KEY_ID"
    key-path: "key/dummy.p8"
jwt:
  secret: 65bdf8966a8af6e65abe300031c6b730eb6d9fca5276eec3506748ff7464540fefcc64b229cae9c1d49888d7845c38c135991f03ed6cd443d593fb763c63314a
  access-token:
    expiration-time: 3600000
  refresh-token:
    expiration-time: 1209600000
# ... 기존 설정들 ...
frontend:
  base-url: "http://localhost:8080"  # 프론트 없으니 일단 백엔드 주소로 설정
  main-page: "/api/v1/test/success"  # 로그인 성공 시 이동할 임시 주소
  login-fail-page: "/login?error"    # 로그인 실패 시 이동할 주소
  local-url: "http://localhost:3000"
  local-secure-url: "https://localhost:3000"
